[package]
name = "robot"
version = "0.1.0"
edition = "2021"

[lib]
name = "robot"
crate-type = ["staticlib", "cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
