[package]
name = "rust-svg-handler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[lib]
name = "svglib"
crate-type = ["cdylib", "staticlib"] #, "lib"
